name: Heroku Deployment
on:
  push:
    branches:
      - main
jobs:
    herokudeploy:
      name: Deploy to Heroku
      runs-on: ubuntu-latest
      env:
        BACKEND_API_URL: ${{ secrets.BACKEND_API_URL }}
      steps:
        - name: Checkout the code
          uses: actions/checkout@v2
        - name: Deploy af96a99fa-frontend-react-with
          uses: akhileshns/heroku-deploy@v3.12.12
          with:
            heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
            heroku_app_name: 'af96a99fa-frontend-react-with'
            heroku_email: ${{ secrets.HEROKU_EMAIL }}
            usedocker: true
            appdir: frontend_react_with_rest
        - name: Deploy a3db02b64-rest-python
          uses: akhileshns/heroku-deploy@v3.12.12
          with:
            heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
            heroku_app_name: 'a3db02b64-rest-python'
            heroku_email: ${{ secrets.HEROKU_EMAIL }}
            usedocker: true
            appdir: rest_python
