name: Heroku Deployment
on:
  push:
    branches:
      - main
jobs:
    herokudeploy:
      name: Deploy to Heroku
      runs-on: ubuntu-latest
      env:
        BACKEND_API_URL: ${{ secrets.BACKEND_API_URL }}
      steps:
        - name: Checkout the code
          uses: actions/checkout@v2
        - name: Deploy a40ea4a4d-frontend-react-with
          uses: akhileshns/heroku-deploy@v3.12.12
          with:
            heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
            heroku_app_name: 'a40ea4a4d-frontend-react-with'
            heroku_email: ${{ secrets.HEROKU_EMAIL }}
        - name: Deploy a9425b721-rest-python
          uses: akhileshns/heroku-deploy@v3.12.12
          with:
            heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
            heroku_app_name: 'a9425b721-rest-python'
            heroku_email: ${{ secrets.HEROKU_EMAIL }}
