on:
  workflow_run:
    workflows: ['Build Python Rest backend', "frontend"]
    types: [completed]
jobs:
  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v2
        with:
          semantic_version: 18.0.1
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
