name: 'Label stale issues and pull requests'
on:
  workflow_dispatch:
  schedule:
    # Runs every day 10:00 UTC
    - cron: '0 10 * * *'

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v4
        with:
          stale-issue-message: "This issue has been labeled stale because it has been open 60 days with no activity."
          stale-pr-message: "This pull request has been labeled stale because it has been open 5 days with no activity."
          days-before-issue-stale: 60
          days-before-pr-stale: 5
          days-before-close: -1
          days-before-pr-close: -1
